-- 코드를 입력하세요
WITH HOURS (HOUR) AS (
    SELECT 0 AS HOUR
    FROM DUAL
    UNION ALL
    SELECT (H.HOUR + 1) AS HOUR
    FROM HOURS H
    WHERE H.HOUR < 23
), OUTS AS (
    SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR
            , COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
)
SELECT H.*, NVL(O.COUNT, 0) AS COUNT
FROM HOURS H
    LEFT JOIN OUTS O ON H.HOUR = O.HOUR
ORDER BY H.HOUR