-- 코드를 입력하세요
WITH TEMP AS (
    SELECT WRITER_ID, COUNT(*)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)
SELECT U.USER_ID, U.NICKNAME
        , CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소"
        , SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8) AS "전화번호"
FROM USED_GOODS_USER U
    JOIN TEMP T ON U.USER_ID = T.WRITER_ID
ORDER BY U.USER_ID DESC