-- 코드를 입력하세요
WITH TEMP AS (
    SELECT CAR_ID, (END_DATE-START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT CAR_ID, ROUND(AVG(DURATION),1) AS AVERAGE_DURATION
FROM TEMP
GROUP BY CAR_ID
HAVING AVG(DURATION) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC