-- 코드를 입력하세요
WITH TEMP AS(
    SELECT FLAVOR
    FROM (SELECT * FROM FIRST_HALF
          UNION
          SELECT * FROM JULY
         )
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC
)
SELECT *
FROM TEMP
WHERE ROWNUM <= 3