-- 코드를 입력하세요
WITH TEMP AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
SELECT U.USER_ID, U.NICKNAME, T.TOTAL_SALES
FROM TEMP T
    JOIN USED_GOODS_USER U ON T.WRITER_ID = U.USER_ID
ORDER BY T.TOTAL_SALES