-- 코드를 입력하세요
WITH SALES_AMOUNT AS (
SELECT BOOK_ID, SUM(SALES) AS SALES_SUM
FROM BOOK_SALES
WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022
    AND EXTRACT(MONTH FROM SALES_DATE) = 1
GROUP BY BOOK_ID
), TOTAL_SALES AS (
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (S.SALES_SUM * B.PRICE) AS "TOTAL_SALES"
FROM SALES_AMOUNT S
    JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
)
SELECT AUTHOR_ID, MAX(AUTHOR_NAME), CATEGORY, SUM(TOTAL_SALES) AS "TOTAL_SALES"
FROM TOTAL_SALES
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC