-- 코드를 입력하세요
SELECT PRODUCT_CODE AS CATEGORY, COUNT(PRODUCT_ID)
FROM (SELECT PRODUCT_ID
      , SUBSTR(PRODUCT_CODE, 0, 2) AS PRODUCT_CODE
      FROM PRODUCT)
GROUP BY PRODUCT_CODE
ORDER BY PRODUCT_CODE